version: 2
jobs:
  build:
    docker:
      - image: debian:stretch

    steps:
      - checkout

      - run:
          name: Installing sudo
          command: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'

      - run:
          name: Installing dependencies
          command: 'apt-get update && apt-get install -y gcc g++'

      - run:
          name: Installing dependencies
          command: 'apt-get update && sudo apt-get install -y cmake'

      - run:
          name: Installing dependencies
          command: 'apt-get update && sudo apt-get install -y git'

      - run:
          name: Installing Catch libraries
          command: 'git clone https://github.com/catchorg/Catch2.git && cd Catch2 && cmake -Bbuild -H. -DBUILD_TESTING=OFF && sudo cmake --build build/ --target install'

      - run:
          name: Making directories
          command: 'mkdir build'

      - run:
          name: Building
          command: 'cd build && cmake .. && make'

      - run:
          name: Running tests
          command: 'make test'